services:
  # Backend (web service)
  - type: web
    name: smartcart-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    # Corrected field for referencing source directory
    build:
      context: ./REST  # Link to backend directory
    routes:
      - path: "/api/*"  # Correct format for route path (depending on the platform)
    regions:
      - "us-east"  # Ensure your platform supports region selection
  
  # Frontend (web service for static files)
  - type: web
    name: smartcart-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start-local-server"
    # Corrected field for referencing source directory
    build:
      context: ./PWA  # Link to frontend directory
    routes:
      - path: "/login.html"
    regions:
      - "us-east"  # Ensure your platform supports region selection