services:
  # Backend (web service)
  - type: web
    name: smartcart-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    # Define the backend directory for Render
    autoDeploy: true  # Automatically deploy on new commits
    envVars:  # Optional: define environment variables if needed
      - key: NODE_ENV
        value: production

  # Frontend (web service for static files)
  - type: web
    name: smartcart-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start-local-server"
    # Define the frontend directory for Render
    autoDeploy: true  # Automatically deploy on new commits
    envVars:  # Optional: define environment variables if needed
      - key: NODE_ENV
        value: production