services:
  # Backend (web service)
  - type: web
    name: smartcart-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    source: ./REST  # Povezava do mape z backend kodo
    instances: 1
    routes:
      - "/api/*"  # API poti
    regions:
      - "us-east"

  # Frontend (web service for static files)
  - type: web
    name: smartcart-frontend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start-local-server"
    source: ./PWA  # Povezava do mape s frontendom
    instances: 1
    routes:
      - "/login.html"
    regions:
      - "us-east"